/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.wreulicke.log4j2;

import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

class LibraryTest {
    Logger logger = LoggerFactory.getLogger(LibraryTest.class);

    @Test
    void simple() {
        logger.info("test");

        logger.atInfo().addKeyValue("key", "value").log("test");
    }

    @Test
    void nested() {
        // 出力結果はこうなる
        // {"mdc":{"key":"Nested[value=value]"},"@version":1,"message":"test","thread_name":"Test worker","@timestamp":"2024-08-27T02:06:17.963+0900","level":"INFO","logger_name":"com.github.wreulicke.log4j2.LibraryTest"}
        //
        // "mdc":{"key":"Nested[value=value]"} となってしまい、
        // "mdc":{"key": { "value": "value" } } とはならない
        logger.atInfo().addKeyValue("key", new Nested("value")).log("test");
    }

    record Nested(String value) {
    }
}
