/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.wreulicke.logback;

import net.logstash.logback.argument.StructuredArguments;
import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    Logger logger = LoggerFactory.getLogger(LibraryTest.class);

    @Test
    void simple() {
        logger.info("test");

        logger.info("test", StructuredArguments.keyValue("key", "value"));

        logger.atInfo().addKeyValue("key", "value").log("test");
    }

    @Test
    void nested() {
        logger.info("test", StructuredArguments.keyValue("key", new Nested("value")));

        logger.atInfo().addKeyValue("key", new Nested("value")).log("test");
    }

    record Nested(String value) {
    }
}
